apiVersion: v1
kind: PersistentVolume
metadata:
  name: morp-pv
  namespace: morp
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: morp-local-storage
  local:
    path: /mnt/morp
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - kube-worker-03
